<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>{{ $quote->quote_ref }} — Motor Insurance Quote</title>
    <style>
        * { box-sizing: border-box; }
        body { font-family: 'DejaVu Sans', Helvetica, Arial, sans-serif; color: #111; font-size: 13px; margin: 0; padding: 32px; }
        .letterhead { display: flex; justify-content: space-between; align-items: flex-start; border-bottom: 3px solid #2a78d6; padding-bottom: 12px; margin-bottom: 20px; }
        .brand { display: flex; align-items: center; gap: 10px; }
        .brand img { width: 44px; height: 44px; object-fit: contain; }
        .letterhead h1 { font-size: 16px; margin: 0; color: #184f95; }
        .letterhead p { margin: 2px 0 0; font-size: 11px; color: #555; }
        .doc-title { text-align: right; }
        .doc-title h2 { margin: 0; font-size: 15px; text-transform: uppercase; letter-spacing: 0.05em; }
        .doc-title p { margin: 2px 0 0; font-size: 11px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { text-align: left; padding: 6px 8px; border: 1px solid #ddd; font-size: 12px; }
        th { background: #f2f6fc; }
        .section-title { font-size: 13px; font-weight: bold; margin: 22px 0 6px; color: #184f95; }
        .kv { display: grid; grid-template-columns: repeat(3, 1fr); gap: 14px 20px; margin-top: 6px; }
        .kv label { display: block; font-size: 10px; text-transform: uppercase; color: #888; }
        .kv span { font-size: 13px; font-weight: 600; }
        .premium-box { border: 1px solid #ddd; border-radius: 6px; padding: 12px 16px; margin-top: 10px; width: 300px; margin-left: auto; }
        .premium-box .row { display: flex; justify-content: space-between; padding: 3px 0; font-size: 12px; }
        .premium-box .total { border-top: 1px solid #ccc; margin-top: 6px; padding-top: 6px; font-weight: bold; font-size: 13px; }
        .footer-note { margin-top: 28px; font-size: 10px; color: #888; }
    </style>
</head>
<body onload="window.print()">
    <div class="letterhead">
        <div class="brand">
            <img src="{{ $logo }}" alt="Stronghold">
            <div>
                <h1>Stronghold</h1>
                <p>InsurApp — SICI Producers' Portal</p>
            </div>
        </div>
        <div class="doc-title">
            <h2>Motor Insurance Quote</h2>
            <p>Quote Ref. {{ $quote->quote_ref }}</p>
        </div>
    </div>

    <div class="kv">
        <div><label>Created</label><span>{{ $quote->created_at->format('M d, Y g:i A') }}</span></div>
        <div><label>Vehicle</label><span>{{ $quote->vehicle_title }}</span></div>
        <div><label>Plate No.</label><span>{{ $quote->plate_no }}</span></div>
        <div><label>Registration Type</label><span>{{ $quote->lto_registration_type }}</span></div>
        <div><label>Vehicle Class</label><span>{{ $quote->vehicle_class }}</span></div>
        <div><label>Coverage Period</label><span>{{ $quote->coverage_period }} Year(s)</span></div>
        <div><label>Producer</label><span>{{ $quote->producer->code }} — {{ $quote->producer->full_name }}</span></div>
    </div>

    <p class="section-title">Peril/s Covered</p>
    <table>
        <thead>
            <tr><th>Peril/s Covered</th><th>Sum Insured</th><th>Premium</th></tr>
        </thead>
        <tbody>
            <tr>
                <td>Compulsory Liability: Bodily Injury/Death (CTPL)</td>
                <td>₱{{ number_format(200000, 2) }}</td>
                <td>₱{{ number_format($quote->net_premium, 2) }}</td>
            </tr>
        </tbody>
    </table>

    <p class="section-title">Premium Due</p>
    <div class="premium-box">
        <div class="row"><span>Net Premium</span><span>₱{{ number_format($quote->net_premium, 2) }}</span></div>
        <div class="row"><span>Documentary Stamps Tax</span><span>₱{{ number_format($quote->doc_stamps_tax, 2) }}</span></div>
        <div class="row"><span>Value Added Tax</span><span>₱{{ number_format($quote->vat, 2) }}</span></div>
        <div class="row"><span>Local Government Tax</span><span>₱{{ number_format($quote->local_govt_tax, 2) }}</span></div>
        <div class="row"><span>LTO DBP-DCI Fee</span><span>₱{{ number_format($quote->lto_dbp_dci_fee, 2) }}</span></div>
        <div class="row"><span>COC Verification</span><span>₱{{ number_format($quote->coc_verification_fee, 2) }}</span></div>
        <div class="row"><span>Others</span><span>₱{{ number_format($quote->other_charges, 2) }}</span></div>
        <div class="row total"><span>Total Premium</span><span>₱{{ number_format($quote->total_premium, 2) }}</span></div>
    </div>

    <p class="footer-note">
        This is a quotation only and does not bind Stronghold to provide coverage. Coverage becomes binding only
        upon agreement and full payment of premium. System-generated by InsurApp for demonstration purposes and
        is not a legally binding insurance document. Copyright &copy; 2018-2026 Stronghold. All rights reserved.
    </p>
</body>
</html>
